providers = ["php"]

[phases.setup]
nixPkgs = ["php83", "php83Packages.composer", "php83Extensions.pgsql", "php83Extensions.pdo_pgsql", "php83Extensions.gd", "php83Extensions.mbstring", "php83Extensions.xml", "php83Extensions.curl", "php83Extensions.zip", "php83Extensions.bcmath", "php83Extensions.intl"]

[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader --no-interaction"]

[phases.build]
cmds = ["echo 'Using pre-built frontend assets from git'"]
